version: '3.1'

services:
  jrnl-backend:
    build: .
    image: jrnl-backend
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./src:/usr/src/app/src"
      - "./dist:/usr/src/app/dist"


  jrnl-backend-tests:
    image: jrnl-backend
    command: yarn test -o --watch
    environment:
      APP_URL: http://jrnl-backend:8000
    volumes:
      - "./src:/usr/src/app/src"
    depends_on:
      - jrnl-backend